baseURL = 'https://ruhrpottpatriot.github.io/'
languageCode = 'en-gb'
title = 'My New Hugo Site'
theme = "hugo-book"

[params]
githubName = "Ruhrpottpatriot"
hideHUGOSupport = true

[[menu.main]]  # here are the buttons on the menu
name = "Home" # Button will display as "Home"
weight = 100 # the weight decides the position of the button (higher or lower)
identifier = "home"
pre = "<br />"
url = "/"

[[menu.main]]
name = "About"
identifier = "about" # this page will refer to a markdown file named "blog" in the content folder
pre = "<br />"
url = "/post"
weight = 40
